### ISSUE TITLE
Linux build documentation

### ISSUE THREAD

**Issue by gczark** [twopointzero/TJAPlayer3#55]
WineHQ somehow cannot render the sound correctly, thinking of building the app native for Linux from this source, but just don't know how.

**Comment by EaterOA** [comment]
FWIW, WineHQ works almost perfectly for me (`wine-5.0 (Ubuntu 5.0-3ubuntu1)`, wine-stable in Ubuntu 20.10). No sound issues. Biggest snag during setup was having to grab MS Gothic. The only remaining issue I'm trying to figure out is that it seems to not like `WAVE` paths with Japanese characters (whether the TJA file is in SHIFT-JIS or in UTF-8). Not expecting support, but just a note here for posterity.

**Comment by gczark** [comment]
At some time, I want to fork it to flathub so that it runs natively like citra. But since I have zero code experience, it will not happen any time soon.
