### ISSUE TITLE
how to open 7z file

### ISSUE THREAD

**Issue by oofyXD** [twopointzero/TJAPlayer3#73]
**Please write a description of your request**
the 7z file will open but just duplicate and will not work
![image](https://user-images.githubusercontent.com/76968752/109367317-981ecb00-784a-11eb-8f6d-d4ec97a15675.png)
(after many, many, many opening and self duplicating)

**Please tell us about your environment:**

- TJAPlayer3 version: vX.X.X-yyy
- Operating system version:
- Windows System Locale:
- Display adapter:
- Audio adapter:
- Input device:

**Other information**
can you have it as a exe? or will it only be a 7z file

Here are some suggestions:

- Related issues
- Config.ini file
- Skin *Config.ini files
- Stack trace(s)
- Log file(s)
- Example .tja file(s) (do *not* provide media)

**Comment by twopointzero** [comment]
Hi @oofyXD. There appears to be an issue with your installed 7-Zip software, or with your Windows installation more generally. Please ensure 7-Zip is installed and up to date and, once that has been confirmed, perhaps try opening the TJAPlayer3 archive file via right-click, navigating to the 7-Zip menu option there, and trying using one of the "open" or "extract" choices available.

**Comment by oofyXD** [comment]
i don't think 7-zip is downloaded on this computer. ill try to find it on the internet

**Comment by oofyXD** [comment]
sorry for reopening this but my other computer works but I cannot download it. it just says something about being to dangerous to download. when I open the 7z file is it supposed open up winzip trial? im really confused

**Comment by twopointzero** [comment]
Hey oofyXD. I'm sorry to hear that you're still having trouble but am afraid I cannot help much beyond suggesting that you need installed, working 7-Zip archive software. 7-Zip shaves quite a few bits off the release sizes relative to old-school zip. Please try installing and using the version appropriate to your computer, from here if you've not already: https://www.7-zip.org/

**Comment by oofyXD** [comment]
opened it!
